name: Heroku Deploy

on:
  push:
    branches:
      - master

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container
        run:  docker build -t finger-guns -f Dockerfile --build-arg token=${{secrets.SLACK_USER_TOKEN}} --build-arg api=${{secrets.SLACK_API_URL}} .

      - name: Heroku login
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login

      - name: Push Container
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:push -a ${{secrets.HEROKU_APP_NAME}} finger-guns

      - name: Release Container
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:release -a ${{secrets.HEROKU_APP_NAME}} finger-guns